<?php
// Generated by Zend Framework 2
return array(
    'Auth\Module'                   => __DIR__ . '/Module.php',
    'Auth\Model\AuthOrNot'          => __DIR__ . '/src/Auth/Model/AuthOrNot.php',
    'Auth\Session\BootstrapSession' => __DIR__ . '/src/Auth/Session/BootstrapSession.php',
    'Auth\Session\SessionManager'   => __DIR__ . '/src/Auth/Session/SessionManager.php',
);
